[tools]
chezmoi = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "latest"
node = "22"
python = "3.10"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
zoxide = "latest"
